//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Activities.Exaone {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Activities.Exaone.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   API키과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApiKey_DisplayName {
            get {
                return ResourceManager.GetString("ApiKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exaon API키과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApiKey_Placeholder {
            get {
                return ResourceManager.GetString("ApiKey_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exaon API키과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApiKey_Tooltip {
            get {
                return ResourceManager.GetString("ApiKey_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인용 문자열과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CitationText_DisplayName {
            get {
                return ResourceManager.GetString("CitationText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   벡터 검색을 통해 참고된 컨텍스트 정보입니다. AI 응답의 기반이 된 인용 정보가 포함됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CitationText_Tooltip {
            get {
                return ResourceManager.GetString("CitationText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터베이스의 모든 내용을 삭제하여 초기화합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClearDatabase_Description {
            get {
                return ResourceManager.GetString("ClearDatabase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터베이스 초기화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClearDatabase_DisplayName {
            get {
                return ResourceManager.GetString("ClearDatabase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채팅 자동 완성 모델을 사용하여 제공된 요청에 대한 채팅 응답 생성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContentGeneration_Description {
            get {
                return ResourceManager.GetString("ContentGeneration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content Generation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContentGeneration_DisplayName {
            get {
                return ResourceManager.GetString("ContentGeneration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨텍스트 그라운딩과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextGrounding_DisplayName {
            get {
                return ResourceManager.GetString("ContextGrounding_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨텍스트에 따라 프롬프트의 기준을 정하여 출력의 품질과 정확도를 높입니다. 이 기능을 사용하면 사용자가 독점 비즈니스 논리 및 지식을 프롬프트에 삽입할 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextGrounding_Tooltip {
            get {
                return ResourceManager.GetString("ContextGrounding_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엔드포인트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Endpoint_DisplayName {
            get {
                return ResourceManager.GetString("Endpoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exaon 엔드포인트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Endpoint_Placeholder {
            get {
                return ResourceManager.GetString("Endpoint_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exaon 엔드포인트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Endpoint_Tooltip {
            get {
                return ResourceManager.GetString("Endpoint_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨텍스트 그라운딩 오류 시 계속 진행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailOnGroundingError_DisplayName {
            get {
                return ResourceManager.GetString("FailOnGroundingError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨텍스트 데이터 로딩에 실패해도 작업을 계속 진행합니다. 체크를 해제하면 실패 시 오류로 중단됩니다.
        ///(기본값: 체크됨)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FailOnGroundingError_Tooltip {
            get {
                return ResourceManager.GetString("FailOnGroundingError_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   텍스트 파일 경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FilePath_DisplayName {
            get {
                return ResourceManager.GetString("FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   텍스트 파일의 전체 경로과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FilePath_Placeholder {
            get {
                return ResourceManager.GetString("FilePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력에 사용할 로컬 텍스트 파일의 경로를 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FilePath_Tooltip {
            get {
                return ResourceManager.GetString("FilePath_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   결과 (JSON_string)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetDBResult_DisplayName {
            get {
                return ResourceManager.GetString("GetDBResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가져온 전체 데이터베이스 결과 (JSON 문자열)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetDBResult_Tooltip {
            get {
                return ResourceManager.GetString("GetDBResult_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터베이스 내 모든 데이터를 가져옵니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetFullDatabase_Description {
            get {
                return ResourceManager.GetString("GetFullDatabase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 데이터베이스 가져오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetFullDatabase_DisplayName {
            get {
                return ResourceManager.GetString("GetFullDatabase_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가장 많이 생성된 텍스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainText_DisplayName {
            get {
                return ResourceManager.GetString("MainText_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exaone API가 생성한 응답 중 가장 많이 생성된 텍스트입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainText_Tooltip {
            get {
                return ResourceManager.GetString("MainText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   응답 메시지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_DisplayName {
            get {
                return ResourceManager.GetString("Message_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 응답 메시지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Tooltip {
            get {
                return ResourceManager.GetString("Message_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최소 유사도 점수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MinimumScore_DisplayName {
            get {
                return ResourceManager.GetString("MinimumScore_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0~1 사이 소수점 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MinimumScore_Placeholder {
            get {
                return ResourceManager.GetString("MinimumScore_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨텍스트에 포함될 최소 유사도 점수를 지정합니다.
        ///지정된 값보다 낮은 결과는 제외됩니다. (0~1 사이)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MinimumScore_Tooltip {
            get {
                return ResourceManager.GetString("MinimumScore_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   모델 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Model_DisplayName {
            get {
                return ResourceManager.GetString("Model_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채팅 자동 완성에 사용할 모델 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Model_Placeholder {
            get {
                return ResourceManager.GetString("Model_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   채팅 자동 완성에 사용할 모델 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Model_Tooltip {
            get {
                return ResourceManager.GetString("Model_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   텍스트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RawTextInput_DisplayName {
            get {
                return ResourceManager.GetString("RawTextInput_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   텍스트 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RawTextInput_Placeholder {
            get {
                return ResourceManager.GetString("RawTextInput_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨텍스트로 활용할 텍스트를 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RawTextInput_Tooltip {
            get {
                return ResourceManager.GetString("RawTextInput_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체 결과과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Result_DisplayName {
            get {
                return ResourceManager.GetString("Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exaone API가 생성한 응답 전체 결과입니다. (JSON 문자열)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Result_Tooltip {
            get {
                return ResourceManager.GetString("Result_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유사도 점수 포함과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Score_DisplayName {
            get {
                return ResourceManager.GetString("Score_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색된 컨텍스트에 유사도 점수를 포함할지 여부를 결정합니다. (기본값: 체크됨)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Score_Tooltip {
            get {
                return ResourceManager.GetString("Score_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색 쿼리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchQuery_DisplayName {
            get {
                return ResourceManager.GetString("SearchQuery_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색하고 싶은 텍스트를 입력하세요. (예: 키워드, 문장 등)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchQuery_Placeholder {
            get {
                return ResourceManager.GetString("SearchQuery_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검색하고 싶은 텍스트를 입력하세요. (예: 키워드, 문장 등)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SearchQuery_Tooltip {
            get {
                return ResourceManager.GetString("SearchQuery_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   응답 상태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusCode_DisplayName {
            get {
                return ResourceManager.GetString("StatusCode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API 응답 상태 코드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StatusCode_Tooltip {
            get {
                return ResourceManager.GetString("StatusCode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템 프롬프트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemPrompt_DisplayName {
            get {
                return ResourceManager.GetString("SystemPrompt_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템이 제공하는 기본 프롬프트 (선택 사항)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemPrompt_Placeholder {
            get {
                return ResourceManager.GetString("SystemPrompt_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시스템이 제공하는 기본 프롬프트 (선택 사항)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SystemPrompt_Tooltip {
            get {
                return ResourceManager.GetString("SystemPrompt_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   온도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Temperature_DisplayName {
            get {
                return ResourceManager.GetString("Temperature_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0~1 사이 소수점 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Temperature_Placeholder {
            get {
                return ResourceManager.GetString("Temperature_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   텍스트 생성의 창의성 요소 조정 (0~1 사이)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Temperature_Tooltip {
            get {
                return ResourceManager.GetString("Temperature_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨텍스트 검색 결과 개수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Top_K_DisplayName {
            get {
                return ResourceManager.GetString("Top_K_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1~5 사이 인수 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Top_K_Placeholder {
            get {
                return ResourceManager.GetString("Top_K_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   응답에 참고할 컨텍스트 문서의 최대 개수를 설정합니다. (VectorDB에서 검색된 결과 수입니다.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Top_K_Tooltip {
            get {
                return ResourceManager.GetString("Top_K_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Url_DisplayName {
            get {
                return ResourceManager.GetString("Url_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL 입력과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Url_Placeholder {
            get {
                return ResourceManager.GetString("Url_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   컨텍스트로 사용할 웹페이지의 주소(URL)를 입력합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Url_Tooltip {
            get {
                return ResourceManager.GetString("Url_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유저 프롬프트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserPrompt_DisplayName {
            get {
                return ResourceManager.GetString("UserPrompt_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 질문 또는 요청 텍스트를 입력합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserPrompt_Placeholder {
            get {
                return ResourceManager.GetString("UserPrompt_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 질문 또는 요청 텍스트를 입력합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UserPrompt_Tooltip {
            get {
                return ResourceManager.GetString("UserPrompt_Tooltip", resourceCulture);
            }
        }
    }
}
